services:
  export-html:
    container_name: export-html
    platform: linux/amd64
    volumes:
      - ./src:/service/src
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      EXPORT_HTML_BEARER_TOKEN: ${EXPORT_HTML_BEARER_TOKEN:?set EXPORT_HTML_BEARER_TOKEN}
    ports:
      - "2305:2305"
